<?php
/**
 *
 *
 * PHP version 5
 *
 * @package
 * @author  Andrey Filippov <afi@i-loto.ru>
 */

namespace App\CLI;

use Dizel\CliController;
use Slim\Http\Environment;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class Help extends CliController
{

	public function getArg($idx)
	{
		return $_SERVER["argv"][$idx];
	}

	public function getArgs()
	{
		/** @var $env Environment*/
		$env = $this->container->get("environment");
		return $_SERVER["argv"];
	}

	protected function execute(InputInterface $input, OutputInterface $output)
	{
		$output->write("lalala HEPL HPELPE");
//		print_r(__CLASS__);
		return 0;
//		parent::execute($input, $output); // TODO: Change the autogenerated stub
	}

//	/**
//	 * @param Request $request
//	 * @param Response $response
//	 * @param array $args
//	 *
//	 * @return Response
//	 */
//	public function preExecute(Request $request, Response $response, array $args)
//	{
//		// TODO: Implement preExecute() method.
//	}
//
//	/**
//	 * @param Request $request
//	 * @param Response $response
//	 * @param array $args
//	 *
//	 * @return Response
//	 */
//	public function execute(Request $request, Response $response, array $args)
//	{
//
////		print_r($this->container);
////		print_r($this->getArgs());
//		return $response->write("!!HELP!!");
////		throw new \Exception("dfdf");
////		return $response->write("!!!")->withStatus(500);
////		print_r("!!!!!");
//	}
}

